# -*- coding: utf-8 -*-
"""Copy of scratchpad

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1djFaVccXke514Cvuu9x9QiMxzmVEOhxd
"""

import random

def hangman():
    # 1. List of 5 predefined words
    word_list = ["python", "code", "alpha", "intern", "skill"]

    # Pick a random word from the list
    word = random.choice(word_list)
    guessed_word = ['_'] * len(word)
    guessed_letters = []
    incorrect_guesses = 0
    max_guesses = 6 # 2. Limit to 6 incorrect guesses

    print("=== Hangman Game ===")
    print("Guess the word one letter at a time.")

    # 3. While loop for the game
    while incorrect_guesses < max_guesses:
        print("\nWord:", " ".join(guessed_word))
        print("Guessed letters:", ", ".join(guessed_letters))
        print("Incorrect guesses left:", max_guesses - incorrect_guesses)

        guess = input("Enter a letter: ").lower()

        # Input validation
        if len(guess)!= 1 or not guess.isalpha():
            print("Enter only one letter a-z.")
            continue

        if guess in guessed_letters:
            print("You already guessed that letter.")
            continue

        guessed_letters.append(guess)

        # 4. If-else to check guess
        if guess in word:
            print("Good guess!")
            for i in range(len(word)):
                if word[i] == guess:
                    guessed_word[i] = guess
        else:
            print("Wrong guess.")
            incorrect_guesses += 1

        # Check if player won
        if '_' not in guessed_word:
            print("\nYou won! The word was:", word)
            break

    # Check if player lost
    if incorrect_guesses == max_guesses:
        print("\nGame over! The word was:", word)

# Run the game
hangman()